'use strict';

module.exports = /** @type {import("@cspell/cspell-types").FileSettings} */ ({
  files: ['**/*.*'],
  ignorePaths: ['/node_modules', '/output', 'package-lock.json', 'package.json', '/data', '/pages', 'apollo/types', '/types/driivz/gateway/driivz-api.schema.ts'],
  ignoreWords: [],
  language: 'en-US',
  version: '0.2',
  words: [
    'ADDNREMOVECHARGER',
    'removecharger-qaautomation',
    'Parens',
    'evseId',
    'RFID',
    "EVgo's",
    'EVgo',
    'evses',
    'apollographql',
    'bytecode',
    'camelcase',
    'codeceptjs',
    'codegen',
    'commandline',
    'coreutils',
    'dnsutils',
    'doctorwho',
    'evgo',
    'fcms',
    'listbox',
    'mailslurp',
    'networkidle',
    'networkidle0',
    'nslookup',
    'promocode',
    'reportal',
    'reportals',
    'requestfinished',
    'resemblehelper',
    'resemblejs',
    'testid',
    'testrail',
    'wdio',
    'webdriverio',
    'Driivz',
    'KOTEFIRSTPLAN',
    'OPKOTEPLAN',
    'subMenuselect',
    'HWKB',
    'Cardk',
    'EVSE',
    'totalk',
    'Detailsk',
    'dont',
    'timeframe',
    'DCQC',
    'Chargerbots',
    'shuf',
    'PAYGO',
  ],
});
